### ISSUE TITLE
Replace 'thresholdRMSXXX' with 'signalRMSXXX'; and 'thresholdMean' with 'signalMean'

### ISSUE THREAD

**Issue by edkangdev** [JaneliaAPIG/spoke#22]
The prop names thresholdRMSXXX and thresholdMean really pertain to the data signals at each logical channel, not to any 'threshold signal'. The current names are confusing in operations using these properties.

**Comment by vijayiyer05** [comment]
Fixed as of 8cc43a677710780efec4e7961c8092237bd4aef7
Use "baselineXXX" and "baselineStatsXXX" nomenclature
