### ISSUE TITLE
Port to Current Spike GLX: First Order/Functional

### ISSUE THREAD

**Issue by edkangdev** [JaneliaAPIG/spoke#27]

**Comment by JaneliaAPIG** [comment]
Works in first-pass bench testing as of d13767a.

Further testing needed to close

**Comment by vijayiyer05** [comment]
Now working in first-pass bench & initial rig testing with current SpikeGLX (v.20160806).

**Comment by vijayiyer05** [comment]
Two passes of testing (both bench & rig) and no issues found related to Spoke. Closing issue.
