### ISSUE TITLE
Stimulus triggered waveform display (Hantman Lab)

### ISSUE THREAD

**Issue by edkangdev** [JaneliaAPIG/spoke#32]

**Comment by edkangdev** [comment]
sync signal, clarify mode - is it similar to, or the same as gate mode? Or is gate mode a precondition for implementation?

**Comment by JaneliaAPIG** [comment]
Austin Graves in Hantman lab requests this feature. It's a hybrid of the classic Waveform & Raster display modes. It's Waveform display mode, but with the selective display based on a (common) stimulus channel, rather than spike detection at each channel. 

Since Raster mode already implements stimulus triggering, user implementation would use the same stimulus channel property that's specified for  Raster mode.

**Comment by JaneliaAPIG** [comment]
If stimulus is never detected, there will never be anything displayed. Only display the signal whenever the stimulus is detected.

**Comment by JaneliaAPIG** [comment]
This feature is basically no longer spike detection.

**Comment by vijayiyer05** [comment]
Appears fixed as of e283c9f3b38183c6d8eaa6850828d2d563698e3e

needs bench testing; also need to check to see if raster mode is still working after all the changes

**Comment by vijayiyer05** [comment]
Appears working as of cfe63442a7fee757329cd2b858d02cc5fd9523e4

* Rig tested
* Raster mode restored

**Comment by vijayiyer05** [comment]
Future issues discovered during work on this issue: 

* [Issue 53](https://github.com/JaneliaAPIG/spoke/issues/53)
** This limits the max stimulus rate for a given timer period

* [Issue 55](https://github.com/JaneliaAPIG/spoke/issues/55)
** This can cause some stimuli to be missed, in rare cases. For r1.0, Spoke does not guarantee all stimuli are processed.

* [Issue 56](https://github.com/JaneliaAPIG/spoke/issues/56)

* [Issue 57](https://github.com/JaneliaAPIG/spoke/issues/57)

**Comment by vijayiyer05** [comment]
Rig demo uncovered a sporadic issue with stim-triggered waveform. Fixed as of fbf8107f17ec2418613c543e2f8ef63051ef3f1e. Tested on rig.

Commit 2df4564daafdb7cfc4faca1b427751f4bbb5aaed cleans up that fix in the code. Tested on bench, though not yet on rig. Presumed working.
